#!/bin/sh
# -----------------------------------------------------------------------------
# File         : generate-design
# Description  : front-end for VHDL synthesis, IDSP version
# Author       : Sabih Gerez, University of Twente
# Creation date: March 17, 2018
# -----------------------------------------------------------------------------
# $Rev: 1$
# $Author: gerezsh$
# $Date: Mon Feb 20 23:36:12 CET 2023$
# $Log$
# -----------------------------------------------------------------------------



# List all source files necessary for the synthesis here.
# Use a backslash ('\') as the last character to end a line and continue 
# on the next.

SOURCE_FILE_LIST="arx_numeric.vhd sec_df2.vhd"
# SOURCE_FILE_LIST="arx_numeric.vhd sec_nov.vhd"

# Declare here the top-level entity. This name should correspond to the
# real entity.

TOP_ENTITY="sec_df2_std"
# TOP_ENTITY="sec_nov_std"

# Declare the top-level architecture. This does not need to correspond
# to a read VHDL architecture name and is only used to give the
# synthesized result a unique name.

TOP_ARCH="rtl"

# Declare here the name of the clock signal

CLOCK="clock"

# List here the word lengths for which the design should be
# synthesized.

# set WORD_LENGTHS to "none" if the design does not have generic
# "word_length"
WORD_LENGTHS="none"

# List here the clock periods for which the design should be
# synthesized. Note: clock periods that make sense normally depend on
# the word length.

CLOCK_PERIODS="10"
# CLOCK_PERIODS="5 4 3 2"

# give INSERT_SCAN a value of "y" if you want a scan chain
INSERT_SCAN=n

# *** DO NOT EDIT BELOW THIS LINE ********************************************

. $SOC_ROOT/scripts/generate-design-core04
