#!/bin/sh
# the line below is a qsub pseudo-comment; do not touch!
#$ -S /bin/sh -cwd
# -----------------------------------------------------------------------------
# File: generate-design
# Description: batch script for synthesizing gate-level circuits from RTL VHDL
# Author: Sabih Gerez, University of Twente
# Creation date: Sat Aug  7 16:42:01 CEST 2004
# -----------------------------------------------------------------------------
# $Rev: 1$
# $Author: gerezsh$
# $Date: Sun Mar 19 22:36:35 CET 2023$
# $Log$
# -----------------------------------------------------------------------------


# List all source files necessary for the synthesis here.
# Use a backslash ('\') as the last character to end a line and continue 
# on the next.

# SOURCE_FILE_LIST="siso_gen_ent.vhd siso_gen_copy_arch.vhd"

# comment the line above and uncomment those below for the synthesis
# of the other designs.

SOURCE_FILE_LIST="arx_numeric.vhd \
                  pk_gfsk.vhd \
                  clock_gen.vhd \
                  demodulator.vhd \
                  filter.vhd \
                  mixer.vhd \
                  slicer.vhd \
                  gfsk.vhd"

# Declare here the top-level entity. This name should correspond to the
# real entity.

TOP_ENTITY="gfsk"

# Declare the top-level architecture. This does not need to correspond
# to a read VHDL architecture name and is only used to give the
# synthesized result a unique name.

TOP_ARCH="structure"

# Declare here the name of the clock signal

CLOCK="clk"
# CLOCK="clock"

# List here the word lengths for which the design should be
# synthesized.

# set WORD_LENGTHS to "none" if the design does not have generic
# "word_length"
WORD_LENGTHS="none"

# List here the clock periods for which the design should be
# synthesized. Note: clock periods that make sense normally depend on
# the word length.

CLOCK_PERIODS="10"
# CLOCK_PERIODS="5 4 3 2"

# give INSERT_SCAN a value of "y" if you want a scan chain
INSERT_SCAN=n

# *** DO NOT EDIT BELOW THIS LINE ********************************************

. $SOC_ROOT/scripts/generate-design-core04
